### PR TITLE
Add test for object axis facing addressee

### PR DESCRIPTION
**Pull request by elizlee**
WIP

### CODE REVIEW

**Comment by gabbard** [comment]
@elizlee : can you remind me the status of this? Is it ready to be reviewed and merged?

**Comment by elizlee** [comment]
@gabbard : I pushed this when I was working on finding a situation that would fail when we had that issue with the axis IDs. In its current state, this test would not be able to catch it if the issue came up again, but otherwise the code is fine...

**Comment by gabbard** [comment]
@elizlee : can you elaborate on " In its current state, this test would not be able to catch it if the issue came up again"?  If the test wouldn't catch anything, should we close the PR?

**Comment by elizlee** [comment]
@gabbard : I think we can close the PR.

**Pull request closed without merging**
