### PR TITLE
Update Travis to specify python 3.7.11

### PR DESCRIPTION
**Pull request by lichtefeld**

### CODE REVIEW

**Review by spigo900 — APPROVED** [review]

**Comment by lichtefeld** [comment]
@spigo900 The precommit checks pass for you locally correct? They pass for me, trying to isolate why Travis keeps having issues I can't reproduce locally. :)

**Comment by spigo900** [comment]
@lichtefeld Pre-commit checks pass for me with no fatal errors. There is a part that modifies `requirements_lock.txt`, though I don't know if that's related. Otherwise, I get a lot (151) of nonfatal and not too serious warnings about things in the documentation. I am running Python 3.7.12 locally, though that shouldn't matter.

**Comment by lichtefeld** [comment]
Ok, I just built an entire new environment on my machine (using python 3.7.13) and it builds fine. I'm going to just move on from troubleshooting travis at the moment because its not worth it until it blocks a PR from either of us rather than the dependabot update which shouldn't even be causing the python code to fail as its updating Angular dependencies!

**Comment by lichtefeld** [comment]
Closing and will address travis issues on another branch.

**Pull request closed without merging**
