### PR TITLE
Display speaker information

### PR DESCRIPTION
**Pull request by LichMaster98**
Closes https://github.com/isi-vista/adam/issues/189

### CODE REVIEW

**Comment by LichMaster98** [comment]
Waiting on https://github.com/isi-vista/adam/pull/256 for testing

**Comment by LichMaster98** [comment]
image

**Comment by marjorief** [comment]
@rgabbard , @LichMaster98 does this change require a a change to the instructions is "Dad says..." the language that the learners hears, or is the fact that someone is saying something a part of the perception of the scene.

**Comment by LichMaster98** [comment]
@marjorief The phrasing of `Dad says "Mom gave me the ball"` is designated to give the reader an easier understanding of who "me" is. It takes the language from being a floating voice to a specific speaker. The learner does perceive who `IS_SPEAKER`.

**Comment by rgabbard** [comment]
@marjorief : "Dad says" is not part of the language the learner hears; rather, the learner knows it is Dad who utters the language.  It would be good to add something on this to the instructions.

**Comment by marjorief** [comment]
IMO, we would want the `Dad Says` to appear as a feature in the perception column. @rgabbard lmk if given where we are, I should just make a change to the instructions that says. 

"Language is typically the language presented to learner. When the speaker is a part of the scene  , this column also includes an attribution statement (e.g. Dad says..) which is not presented to the learner (but rather a part of what the learner perceives.) ."

**Comment by rgabbard** [comment]
We do represent it in the perception, but there is so much stuff there it is difficult to pick out, so I think adding to the instructions as you suggest is good

**Comment by marjorief** [comment]
OK. I've changed the instructions.

**Pull request merged**
