### PR TITLE
Bring precommit checks to Angular App

### PR DESCRIPTION
**Pull request by lichtefeld**
This PR brings the prettier and angular linting checks to the angular app.

Travis should also run the checks, will verify once tests are complete.

### CODE REVIEW

**Comment by gayatri1205** [comment]
Travis's build failed too. Looking into this to check what caused the issue

**Comment by lichtefeld** [comment]
It seems like Travis doesn't like the `*.md` wildcard operator while my local machine handles that fine. I can just list every file there which is a `.md` file...

**Comment by lichtefeld** [comment]
Travis currently isn't running automated checks on the angular portion of the code. I'll look into having it do so but on a lower priority than some other tasks.

**Review by danielnapierski — APPROVED** [review]
All these changes look good.

**Pull request merged**
